import type { Express, Request, Response } from "express";
import { DecisionStore } from "../lib/decision/decision_store.js";

function esc(s: any) {
  return String(s ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function q(req: Request, key: string) {
  return String((req.query as any)[key] ?? "").trim();
}

function mustParams(req: Request, res: Response) {
  const tenantId = q(req, "tenantId");
  const k = q(req, "k");
  if (!tenantId || !k) {
    res.status(400).send("missing tenantId or k");
    return null;
  }
  return { tenantId, k };
}

// NOTE: This is a demo-friendly generator.
// It writes a decision entry for the tenant so the UI feels alive.
// (Security hardening later: verify tenant key against registry.)
async function createDemoDecision(tenantId: string) {
  const store = new DecisionStore(tenantId);
  const now = new Date().toISOString();
  const id = `dc_${Date.now()}`;
  const score = 84 + Math.floor(Math.random() * 12); // 84..95
  const tier = score >= 90 ? "GREEN" : score >= 85 ? "AMBER" : "RED";

  const actions =
    tier === "GREEN"
      ? ["Proceed (low risk)", "Send Proof Pack to client", "Mark as archived"]
      : tier === "AMBER"
      ? ["Proceed with caution", "Request missing evidence", "Set follow-up SLA"]
      : ["Pause campaign", "Escalate to lead", "Require written approval"];

  await store.add({
    id,
    createdAt: now,
    title: "Decision Cover — Demo Decision",
    tier,
    score,
    reason:
      tier === "GREEN"
        ? "All required signals are present. Low contradiction."
        : tier === "AMBER"
        ? "Signals acceptable but some fields are missing or weak."
        : "Contradiction detected. Risk too high without more evidence.",
    actions,
    signals: {
      source: "zapier",
      channel: "paid-ads",
      lead: { email: "demo@client.com", company: "Demo Client" },
      notes: "Generated by /ui/decisions/demo",
    },
    evidence: {
      zipPath: "/ui/evidence.zip",
      csvPath: "/ui/export.csv",
    },
    raw: { demo: true },
  });

  return id;
}

function layout(title: string, body: string) {
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${esc(title)}</title>
  <style>
    :root{color-scheme:dark}
    body{margin:0;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial;background:#0a0a0a;color:#eaeaea}
    a{color:#9ae6ff;text-decoration:none}
    .wrap{max-width:1100px;margin:0 auto;padding:22px}
    .hero{display:flex;gap:16px;flex-wrap:wrap;align-items:center;justify-content:space-between;margin:10px 0 18px}
    .h1{font-size:20px;font-weight:700}
    .muted{opacity:.75;font-size:13px;line-height:1.5}
    .row{display:flex;gap:10px;flex-wrap:wrap}
    .btn{display:inline-flex;align-items:center;gap:8px;border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.06);padding:10px 12px;border-radius:12px}
    .btn:hover{background:rgba(255,255,255,.10)}
    .grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}
    @media(max-width:980px){.grid{grid-template-columns:1fr}}
    .card{border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.05);border-radius:16px;padding:14px}
    .top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}
    .tag{font-size:12px;padding:4px 8px;border-radius:999px;border:1px solid rgba(255,255,255,.14);opacity:.9}
    .k{font-size:12px;opacity:.7}
    .big{font-size:16px;font-weight:700;margin:6px 0}
    .hr{height:1px;background:rgba(255,255,255,.10);margin:10px 0}
    .list{margin:0;padding-left:18px}
    .pill{font-size:12px;border:1px dashed rgba(255,255,255,.18);padding:8px 10px;border-radius:12px;opacity:.85}
    .footer{margin-top:14px;opacity:.6;font-size:12px}
  </style>
</head>
<body>
  <div class="wrap">${body}</div>
</body>
</html>`;
}

function tierTag(tier: string) {
  const t = String(tier || "").toUpperCase();
  if (t.includes("GREEN")) return "GREEN";
  if (t.includes("AMBER") || t.includes("YELLOW")) return "AMBER";
  if (t.includes("RED")) return "RED";
  if (t.includes("PURPLE")) return "PURPLE";
  return t || "—";
}

export function mountDecisionsUI(app: Express) {
  // Main UI
  app.get("/ui/decisions", async (req: Request, res: Response) => {
    const p = mustParams(req, res);
    if (!p) return;

    const store = new DecisionStore(p.tenantId);
    const rows = await store.list(25);

    const links = {
      tickets: `/ui/tickets?tenantId=${encodeURIComponent(p.tenantId)}&k=${encodeURIComponent(p.k)}`,
      csv: `/ui/export.csv?tenantId=${encodeURIComponent(p.tenantId)}&k=${encodeURIComponent(p.k)}`,
      zip: `/ui/evidence.zip?tenantId=${encodeURIComponent(p.tenantId)}&k=${encodeURIComponent(p.k)}`,
      setup: `/ui/setup?tenantId=${encodeURIComponent(p.tenantId)}&k=${encodeURIComponent(p.k)}`,
      demo: `/ui/decisions/demo?tenantId=${encodeURIComponent(p.tenantId)}&k=${encodeURIComponent(p.k)}`,
    };

    const hero = `
      <div class="hero">
        <div>
          <div class="h1">Decision Cover™ — Decisions</div>
          <div class="muted">If you must decide, decide with proof. This page shows every decision generated from your intake.</div>
        </div>
        <div class="row">
          <a class="btn" href="${links.demo}">⚡ Generate demo decision</a>
          <a class="btn" href="${links.setup}">🧭 Setup</a>
          <a class="btn" href="${links.tickets}">🎟 Tickets</a>
          <a class="btn" href="${links.csv}">⬇ Export CSV (for reporting)</a>
          <a class="btn" href="${links.zip}">📦 Evidence ZIP</a>
        </div>
      </div>
      <div class="row">
        <div class="pill">Tenant: <span class="k">${esc(p.tenantId)}</span></div>
        <div class="pill">Key: <span class="k">${esc(p.k.slice(0, 8))}…</span></div>
      </div>
    `;

    const cards =
      rows.length === 0
        ? `<div class="card"><div class="big">No decisions yet.</div><div class="muted">Click “Generate demo decision” to see how the product looks for a client.</div></div>`
        : `<div class="grid">${rows
            .map((r) => {
              const tag = tierTag(String((r as any).tier || ""));
              const score = Number((r as any).score ?? 0);
              const title = (r as any).title || "Decision";
              const reason = (r as any).reason || "";
              const actions = Array.isArray((r as any).actions) ? (r as any).actions : [];
              return `
                <div class="card">
                  <div class="top">
                    <div>
                      <div class="k">${esc((r as any).createdAt || "")}</div>
                      <div class="big">${esc(title)}</div>
                    </div>
                    <div class="tag">${esc(tag)} · ${esc(score)}</div>
                  </div>
                  <div class="hr"></div>
                  <div class="muted">${esc(reason)}</div>
                  <div class="hr"></div>
                  <div class="k">Recommended moves</div>
                  <ul class="list">
                    ${actions.slice(0, 3).map((a: any) => `<li>${esc(a)}</li>`).join("")}
                  </ul>
                </div>
              `;
            })
            .join("")}</div>`;

    const body = `${hero}${cards}<div class="footer">Decision Cover™ demo UI. Next: connect real pack ZIP per decision (Phase40).</div>`;
    res.setHeader("content-type", "text/html; charset=utf-8");
    res.status(200).send(layout("Decision Cover — Decisions", body));
  });

  // Demo generator (adds one decision, then redirect back)
  app.get("/ui/decisions/demo", async (req: Request, res: Response) => {
    const p = mustParams(req, res);
    if (!p) return;
    await createDemoDecision(p.tenantId);
    const back = `/ui/decisions?tenantId=${encodeURIComponent(p.tenantId)}&k=${encodeURIComponent(p.k)}`;
    return res.redirect(302, back);
  });
}
